-- MySQL Script generated by MySQL Workbench
-- Fri Apr 15 11:12:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema juego_maya
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `juego_maya` ;

-- -----------------------------------------------------
-- Schema juego_maya
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `juego_maya` DEFAULT CHARACTER SET utf8 ;
USE `juego_maya` ;

-- -----------------------------------------------------
-- Table `juego_maya`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`users` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`users` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `birth_date` DATETIME NOT NULL,
  `creation_date` DATETIME NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_maya`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`games` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`games` (
  `id_game` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `total_levels` INT NOT NULL,
  PRIMARY KEY (`id_game`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_maya`.`levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`levels` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`levels` (
  `level_order` INT NOT NULL AUTO_INCREMENT,
  `total_score` INT NOT NULL,
  `minimum_score` INT NOT NULL,
  `id_previousLevel` INT NOT NULL,
  `id_nextLevel` INT NOT NULL,
  `id_game` INT NOT NULL,
  PRIMARY KEY (`level_order`, `id_game`),
  INDEX `fk_levels_levels_idx` (`id_previousLevel` ASC) VISIBLE,
  INDEX `fk_levels_levels1_idx` (`id_nextLevel` ASC) VISIBLE,
  INDEX `fk_levels_games1_idx` (`id_game` ASC) VISIBLE,
  CONSTRAINT `fk_levels_levels`
    FOREIGN KEY (`id_previousLevel`)
    REFERENCES `juego_maya`.`levels` (`level_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_levels_levels1`
    FOREIGN KEY (`id_nextLevel`)
    REFERENCES `juego_maya`.`levels` (`level_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_levels_games1`
    FOREIGN KEY (`id_game`)
    REFERENCES `juego_maya`.`games` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_maya`.`user_progress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`user_progress` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`user_progress` (
  `username` VARCHAR(50) NOT NULL,
  `id_level` INT NOT NULL,
  `total_score` INT NULL,
  `is_finished` TINYINT(1) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`username`, `id_level`),
  INDEX `fk_user_progress_users1_idx` (`username` ASC) VISIBLE,
  INDEX `fk_user_progress_levels1_idx` (`id_level` ASC) VISIBLE,
  CONSTRAINT `fk_user_progress_users1`
    FOREIGN KEY (`username`)
    REFERENCES `juego_maya`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_progress_levels1`
    FOREIGN KEY (`id_level`)
    REFERENCES `juego_maya`.`levels` (`level_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_maya`.`level_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`level_information` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`level_information` (
  `order_information` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `information` MEDIUMTEXT NOT NULL,
  `id_level` INT NOT NULL,
  PRIMARY KEY (`order_information`, `id_level`),
  CONSTRAINT `fk_level_information_levels1`
    FOREIGN KEY (`id_level`)
    REFERENCES `juego_maya`.`levels` (`level_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_maya`.`level_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`level_questions` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`level_questions` (
  `order_question` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(355) NOT NULL,
  `answer` VARCHAR(255) NOT NULL,
  `score` INT NOT NULL,
  `id_level` INT NOT NULL,
  PRIMARY KEY (`order_question`, `id_level`),
  INDEX `fk_level_questions_levels1_idx` (`id_level` ASC) VISIBLE,
  CONSTRAINT `fk_level_questions_levels1`
    FOREIGN KEY (`id_level`)
    REFERENCES `juego_maya`.`levels` (`level_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_maya`.`level_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`level_images` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`level_images` (
  `id_levelImages` INT NOT NULL,
  `order_information` INT NOT NULL,
  `id_level` INT NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `image_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_levelImages`, `order_information`, `id_level`),
  INDEX `fk_level_informationImages_level_information1_idx` (`order_information` ASC, `id_level` ASC) VISIBLE,
  CONSTRAINT `fk_level_informationImages_level_information1`
    FOREIGN KEY (`order_information` , `id_level`)
    REFERENCES `juego_maya`.`level_information` (`order_information` , `id_level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
