-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 04:33:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema juego_maya
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `juego_maya` ;

-- -----------------------------------------------------
-- Schema juego_maya
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `juego_maya` DEFAULT CHARACTER SET utf8 ;
USE `juego_maya` ;

-- -----------------------------------------------------
-- Table `juego_maya`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`users` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`users` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `birth_date` DATE NOT NULL,
  `creation_date` DATE NOT NULL,
  `total_score` INT NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_maya`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`games` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`games` (
  `id_game` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `win_score` INT NOT NULL,
  `lose_score` INT NULL,
  PRIMARY KEY (`id_game`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_maya`.`users_games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`users_games` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`users_games` (
  `id_usersGames` INT NOT NULL AUTO_INCREMENT,
  `game_time` TIME NOT NULL,
  `change_score` INT NOT NULL,
  `previous_score` INT NOT NULL,
  `new_score` INT NOT NULL,
  `isWinner` TINYINT(1) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `id_game` INT NOT NULL,
  PRIMARY KEY (`id_usersGames`),
  INDEX `fk_wins_users_idx` (`username` ASC) VISIBLE,
  INDEX `fk_wins_games1_idx` (`id_game` ASC) VISIBLE,
  CONSTRAINT `fk_wins_users`
    FOREIGN KEY (`username`)
    REFERENCES `juego_maya`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wins_games1`
    FOREIGN KEY (`id_game`)
    REFERENCES `juego_maya`.`games` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_maya`.`medals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`medals` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`medals` (
  `id_medal` INT NOT NULL AUTO_INCREMENT,
  `name` TIME NOT NULL,
  `required_score` INT NOT NULL,
  `imgPath` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_medal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_maya`.`user_medals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_maya`.`user_medals` ;

CREATE TABLE IF NOT EXISTS `juego_maya`.`user_medals` (
  `id_userMedals` INT NOT NULL AUTO_INCREMENT,
  `creation_date` DATE NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `id_medal` INT NOT NULL,
  PRIMARY KEY (`id_userMedals`),
  INDEX `fk_user_medals_users1_idx` (`username` ASC) VISIBLE,
  INDEX `fk_user_medals_medals1_idx` (`id_medal` ASC) VISIBLE,
  CONSTRAINT `fk_user_medals_users1`
    FOREIGN KEY (`username`)
    REFERENCES `juego_maya`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_medals_medals1`
    FOREIGN KEY (`id_medal`)
    REFERENCES `juego_maya`.`medals` (`id_medal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- View `juego_maya`.`user_ranking`
-- -----------------------------------------------------


CREATE VIEW user_ranking AS 
SELECT username, total_score, dense_rank() OVER(ORDER BY total_score DESC) AS 'ranking' 
FROM users;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
